name: docker-compose-actions-workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Show logs master
        run: docker-compose logs master
      - name: Test connection master database
        run: docker-compose exec -T master pwd 
      - name: Run makemigrations
        run: docker-compose exec -T webapp python manage.py makemigrations 
      - name: Run migrate
        run: docker-compose exec -T webapp python manage.py migrate
      - name: Run test
        run: docker-conpose exec -T webapp python manage.py test
